### ISSUE TITLE
Package tools for installation in scancode.io

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-analyzer#21]
This should be a reasonably easy way to package and install this in scancode.io ideally as a wheel.

- [x] rename the repo to `scancode-analyzer`
- [x] rename the modules to `scancode_analyzer`
- [x] create a webhook for RTD publishing
- [x] Publish the updated doc and rename and check
- [x] Review of the package manifests
- [x] Add an about file at root
- [x] Start using calver versioning
- [x] Merge Open PRs
- [ ] Add and push tag (Possibly `v21.4.7`)
- [ ] Build wheel and sdist and check with twine
- [ ] Publish on pypi

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne I'm not that familiar with the requirements to release a package, I would be super grateful if you point me to some docs for this, and also as of now there are submodules in the src/ folder with different functionalities, so in the exact API design should I look at scancode/deltacode other projects for inspiration? Also this would just have API functions and not anything related to command-line usage right?

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra we are using https://github.com/jaraco/skeleton now.. @majurg can you provide some guidance?

**Comment by pombredanne** [comment]
That would be fulfilled by #23 BTW

**Comment by majurg** [comment]
@AyanSinhaMahapatra Our particular skeleton repo can be found here: https://github.com/nexB/skeleton

Take a look at the minimal documentation here on how to incorporate the : https://github.com/nexB/skeleton/blob/develop/README.rst

If you have questions, ping me on slack or post them here.

**Comment by AyanSinhaMahapatra** [comment]
> That would be fulfilled by #23 BTW

@pombredanne So my question was in the process of packaging this, should successful integration as a post-scan plugin be present as a test here (as a pytest function)? If so, then since it is closely related, should I finish my work with https://github.com/nexB/scancode-toolkit-plugin-cookiecutter to support simple pre and post-scan plugins (and associated docs)? 

And so in that sense, there will be two issues (in that order) I'll be pushing PRs for before I can focus on this fully, those are - 

#14 
#23  

And also #22 because that'd be important for integration.

@majurg Thanks I'm super clear on the git and merge related tasks that are not a problem, I would be having questions on setting up and modifying the wheel/toml/configure scripts to fit this tool, and I'll ask them here.
